### PR TITLE
making modal viewport adjust to window viewport and scroll inside mod…

### PR DESCRIPTION
**Pull request by broncha**
This is a fix for https://github.com/mWater/mwater-portal/issues/717

### CODE REVIEW

**Comment by grassick** [comment]
On Android 4.1 and 4.3, looks like this:

image

You can scroll up and down, but the top starts out of view. This is true even for short modals:

image

A lot of our users are still on 4.3 (fewer on 4.1). We can't ship the app with broken modals, I'm afraid. Can you look at a workaround for this? Use Android Virtual Device to create a 4.3 (api level 18) to test out the solution. I've updated the demo a bit to test out scrolling, feel free to revert.

4.4 is great:

image

**Comment by grassick** [comment]
This is why http://caniuse.com/#feat=viewport-units

**Comment by broncha** [comment]
@grassick using vh to px converter now. Content now scrollable in old browsers as well

**Comment by grassick** [comment]
Perfect!

**Pull request merged**
